packages:
  - "packages/*"

catalog:
  typescript: ~5.6.3
  "@types/node": ^20.14.10
  ts-node: ^10.9.2
  nock: 14.0.0-beta.7
  buffer: ^6.0.3
  zod: ^3.23.8
  rimraf: ^6.0.0
  "@biomejs/biome": ^1.9.4
  "@changesets/cli": ^2.27.9
  tsup: ^8.3.5
